
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 17 00:44:23 CST 2021
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int dividido = 5;
  public static final int cerrar_par = 9;
  public static final int abrir_par = 8;
  public static final int EOF = 0;
  public static final int menos = 3;
  public static final int pow = 6;
  public static final int numero = 10;
  public static final int error = 1;
  public static final int mod = 7;
  public static final int por = 4;
  public static final int mas = 2;
}

